# Build numbering format
name: $(BuildID)

trigger:
  branches:
    include:
    - master
    - feat/*

schedules:
- cron: "0 0 * * Mon"
  displayName: Weekly midnight build
  always: true
  branches:
    include:
    - master
    - releases/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: npm install
  displayName: 'npm install'

- script: npm audit
  displayName: 'Dependency Audit'
  continueOnError: true

- script: npm run lint
  displayName: 'Lint Code'

- script: npm run simple-examples
  displayName: 'Run Examples (simple)'
  env:
    DB_PASSWORD: $(DB_PASSWORD)

- script: npm run optimized-examples
  displayName: 'Run Examples (optimized)'
  env:
    DB_PASSWORD: $(DB_PASSWORD)
