# Build numbering format
name: $(BuildID)

trigger:
  branches:
    include:
    - main
    - feat/*

schedules:
- cron: "0 0 * * Mon"
  displayName: Weekly midnight build
  always: true
  branches:
    include:
    - main
    - releases/*

variables:
  - group: cosmos-mongoapi-demo-vars

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: npm install
  displayName: 'npm install'

- script: npm audit
  displayName: 'Dependency Audit'
  continueOnError: true

- script: npm run lint
  displayName: 'Lint Code'

- script: |
    npm run simple-examples
    npm run optimized-examples
  displayName: 'Run Examples'
  env:
    DB_HOST: $(lib-cosmos-db-host)
    DB_USER: $(lib-cosmos-db-user)
    DB_NAME: $(lib-cosmos-db-name)
    DB_PASSWORD: $(lib-cosmos-db-password)
    DB_PORT: 10255
